services:
  nginx:
    image: nginx:1.23
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80

  backend-soundcloud:
    image: harypham97/hoidanit-backend-soundcloud-public:1.0
    environment:
      PORT: 8001
      MONGO_URL: mongodb+srv://zikzik1234567890:7V3Zt33TZp7mGHyD@cluster0.hylrbq9.mongodb.net/
    ports:
      - 8001:8001

  frontend-nextjs:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
#docker compose -p ducanh-soundcloud up -d
